spring:
    datasource:
        url: jdbc:h2:mem:demo-db
    data:
        jpa:
            repositories:
                bootstrap-mode: default
    jpa:
        hibernate:
            ddl-auto: create
        database-platform: org.hibernate.dialect.H2Dialect
        show-sql: true
        defer-datasource-initialization: true
    h2:
        console:
            enabled: true
            path: /h2
